<a href="https://colab.research.google.com/github/ethvedbitdesjan/AI-ML_Training/blob/main/PyTorchIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import PyTorch
import torch

# Create a tensor
tensor_a = torch.Tensor([1, 2, 3, 4, 5])

# Display the tensor
print("Tensor a:", tensor_a)

Tensor a: tensor([1., 2., 3., 4., 5.])


In [ ]:
sliced_tensor = tensor_a[1:4]

# Display the sliced tensor
print("Sliced tensor:", sliced_tensor)

# Indexing a specific element
element = tensor_a[2]

# Display the element
print("Element at index 2:", element)

Sliced tensor: tensor([2., 3., 4.])
Element at index 2: tensor(3.)


In [ ]:
# Create a tensor
tensor_a = torch.Tensor([1, 2, 3, 4, 5, 6])

# Using view to reshape tensor
reshaped_with_view = tensor_a.view(2, 3)

# Using reshape to reshape tensor
reshaped_with_reshape = tensor_a.reshape(2, 3)

# Display the reshaped tensors
print("\nReshaped with view:")
print(reshaped_with_view)

print("\nReshaped with reshape:")
print(reshaped_with_reshape)


Reshaped with view:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Reshaped with reshape:
tensor([[1., 2., 3.],
        [4., 5., 6.]])


view: Returns a new tensor with the same data but a different shape. The returned tensor shares the same data and must have the same number of elements. Throws an error if the sizes are incompatible.

reshape: Returns a new tensor with the same data but a different shape. It may or may not share the data, depending on how the tensor is stored in memory.

In [ ]:
# Concatenating two tensors
tensor_b = torch.Tensor([6, 7, 8, 9, 10])
concatenated_tensor = torch.cat((tensor_a, tensor_b), 0)

# Display the concatenated tensor
print("Concatenated tensor:", concatenated_tensor)

# Splitting the tensor into chunks
split_tensors = torch.split(concatenated_tensor, 5)

# Display the split tensors
print("Split tensors:", split_tensors)

Concatenated tensor: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  6.,  7.,  8.,  9., 10.])
Split tensors: (tensor([1., 2., 3., 4., 5.]), tensor([6., 6., 7., 8., 9.]), tensor([10.]))


In [ ]:
# Create a 2D tensor
tensor_2d = torch.Tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create a 3D tensor
tensor_3d = torch.Tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

# Create a 6D tensor
tensor_6d = torch.Tensor(2, 2, 2, 2, 2, 2).fill_(1)  # Filling with ones for simplicity

# Display the tensors
print("2D Tensor:")
print(tensor_2d)

# Slicing 2D tensor: Get the first 2 rows and first 2 columns
sliced_2d = tensor_2d[:2, :2]
print("\nSliced 2D tensor (first 2 rows and first 2 columns):")
print(sliced_2d)

2D Tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

Sliced 2D tensor (first 2 rows and first 2 columns):
tensor([[1., 2.],
        [4., 5.]])


In [ ]:
print("\n3D Tensor:")
print(tensor_3d)

# Slicing 3D tensor: Get the first 2 "blocks", all rows, first column
sliced_3d = tensor_3d[:2, :, :1]
print("\nSliced 3D tensor (first 2 blocks, all rows, first column):")
print(sliced_3d)


3D Tensor:
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

Sliced 3D tensor (first 2 blocks, all rows, first column):
tensor([[[1.],
         [3.]],

        [[5.],
         [7.]]])


#Exercises

In [ ]:
import torch

# TODO: Create a 2D tensor of size 5x3 containing random integers between 1 and 10
tensor_a = # Your code here

# TODO: Create a 1D tensor of size 10 containing a sequence from 1 to 10
tensor_b = # Your code here

print("Tensor A:")
print(tensor_a)
print("\nTensor B:")
print(tensor_b)

In [ ]:
# Given the following tensor
tensor_c = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# TODO: Extract the second row from tensor_c
second_row = # Your code here

# TODO: Extract the first and third columns from tensor_c
selected_columns = # Your code here

print("Second Row:")
print(second_row)
print("\nSelected Columns:")
print(selected_columns)

In [ ]:
# Given the following tensor
tensor_d = torch.arange(1, 13)

# TODO: Reshape tensor_d into a 3x4 tensor
reshaped_tensor = # Your code here

print("Reshaped Tensor:")
print(reshaped_tensor)

In [ ]:
# Given the following tensor
tensor_h = torch.arange(1, 13)

# TODO: Reshape tensor_h into a tensor with 4 rows and infer the number of columns using -1
reshaped_tensor_h = # Your code here

print("Reshaped Tensor H:")
print(reshaped_tensor_h)

In [ ]:
# Given the following tensor
tensor_i = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# TODO: Extract the last row from tensor_i using -1
last_row = # Your code here

print("Last Row:")
print(last_row)

In [ ]:
tensor_e = torch.tensor([[1, 2], [3, 4]])
tensor_f = torch.tensor([[5, 6], [7, 8]])

# TODO: Perform element-wise addition of tensor_e and tensor_f
sum_tensor = # Your code here

# TODO: Calculate the mean of tensor_e
mean_tensor_e = # Your code here

# TODO: Perform matrix multiplication of tensor_e and tensor_f
matmul_result = # Your code here

print("Sum Tensor:")
print(sum_tensor)
print("\nMean of Tensor E:")
print(mean_tensor_e)
print("\nMatrix Multiplication Result:")
print(matmul_result)

In [ ]:
# Given the following tensor
tensor_g = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# TODO: Calculate the sum of each row in tensor_g
row_sum = # Your code here

# TODO: Calculate the transpose of tensor_g
transpose_g = # Your code here

print("Row Sum:")
print(row_sum)
print("\nTranspose of Tensor G:")
print(transpose_g)

#PyTorch Models

In [ ]:
import torch.nn as nn

# Define a simple linear layer with 2 input features and 1 output feature
class SimpleLinearLayer(nn.Module):
    def __init__(self):
        super(SimpleLinearLayer, self).__init__()
        self.linear = nn.Linear(2, 1)

# Create an instance of the SimpleLinearLayer
simple_layer = SimpleLinearLayer()

# Display the layer
print("Simple Linear Layer:")
print(simple_layer)

Simple Linear Layer:
SimpleLinearLayer(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)


In [ ]:
# Define a simple feed-forward neural network
class SimpleFeedForwardNN(nn.Module):
    def __init__(self):
        super(SimpleFeedForwardNN, self).__init__()
        self.layer1 = nn.Linear(2, 5)
        self.layer2 = nn.Linear(5, 1)

    def forward(self, x):
        x = self.layer1(x)
        x = torch.relu(x)
        x = self.layer2(x)
        return x

# Create an instance of the SimpleFeedForwardNN
simple_nn = SimpleFeedForwardNN()

# Create a sample input tensor
input_tensor = torch.Tensor([[1.0, 2.0]])

# Forward pass through the network
output_tensor = simple_nn(input_tensor)

# Display the output
print("\nOutput after forward pass:")
print(output_tensor)


Output after forward pass:
tensor([[-0.4920]], grad_fn=<AddmmBackward0>)


In [ ]:
# Exercise: Define a neural network with one hidden layer of size 10
class ExerciseNN(nn.Module):
    def __init__(self):
        super(ExerciseNN, self).__init__()
        self.layer1 = nn.Linear(2, 10)
        self.layer2 = nn.Linear(10, 1)

    def forward(self, x):
        x = self.layer1(x)
        x = torch.relu(x)
        x = self.layer2(x)
        return x

# Create an instance of the ExerciseNN
exercise_nn = ExerciseNN()

# Create a sample input tensor
exercise_input = torch.Tensor([[1.0, 2.0]])

# Forward pass through the network
exercise_output = exercise_nn(exercise_input)

# Display the output
print("\nOutput of the exercise neural network:")
print(exercise_output)


Output of the exercise neural network:
tensor([[-0.0623]], grad_fn=<AddmmBackward0>)


In [ ]:
import torch.optim as optim

# Define a simple feed-forward neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.layer1 = nn.Linear(2, 5)
        self.layer2 = nn.Linear(5, 1)

    def forward(self, x):
        x = self.layer1(x)
        x = torch.relu(x)
        x = self.layer2(x)
        return x

# Create an instance of the SimpleNN
simple_nn = SimpleNN()

# Create a sample input tensor
input_tensor = torch.Tensor([[1.0, 2.0]])

# Create a sample target tensor
target_tensor = torch.Tensor([[0.0]])

# Define a loss function and optimizer
loss_function = nn.MSELoss()
optimizer = optim.SGD(simple_nn.parameters(), lr=0.01)

# Forward pass through the network
output_tensor = simple_nn(input_tensor)

# Compute the loss
loss = loss_function(output_tensor, target_tensor)

# Display the initial loss
print("Initial Loss:", loss.item())

# Zero the gradients
optimizer.zero_grad()

# Backward pass (compute gradients)
loss.backward()

# Update the weights
optimizer.step()

# Forward pass through the network again
output_tensor = simple_nn(input_tensor)

# Compute the new loss
new_loss = loss_function(output_tensor, target_tensor)

# Display the new loss
print("New Loss:", new_loss.item())

Initial Loss: 0.17728237807750702
New Loss: 0.15348653495311737


## Understanding a Simple Neural Network Example in PyTorch

In this example, we define a simple neural network with one hidden layer. We then create a sample input and target tensor, and define a mean squared error loss function and a stochastic gradient descent optimizer.

### Steps in the Example

1. **Forward Pass**: We pass the input through the network to obtain the output.
2. **Compute Loss**: The loss is computed by comparing the output and the target using a mean squared error loss function.
3. **Zero Gradients**: Before performing the backward pass, we zero out the gradients to ensure they do not accumulate.
4. **Backward Pass**: The `loss.backward()` function is called to compute the gradients for all parameters in the network.
5. **Update Weights**: The optimizer updates the weights based on the computed gradients.

### Understanding Backward and Autograd

The `backward()` function computes the gradient of the loss with respect to each parameter using backpropagation. These gradients are stored in each parameter's `.grad` attribute and are used by the optimizer to update the weights.

$$
\text{Gradient of Loss with respect to parameter} = \frac{\partial \text{Loss}}{\partial \text{parameter}}$$

### Conclusion

Feel free to run this code snippet to observe how the loss changes after a single update. This should provide a good understanding of how `backward()` and autograd work in PyTorch.

In [ ]:
from google.colab import drive
drive.mount('content/', force_remount=True)

Mounted at content/


In [ ]:
%cd /content/content/MyDrive/DLab_AI ML_Training

/content/content/MyDrive/DLab_AI ML_Training


In [ ]:
import numpy as np
from torch.utils.data import DataLoader, TensorDataset

In [ ]:
# Load Shakespeare text
with open('input.txt', 'r') as f:
    text = f.read()

text = text.lower()

text[:100]

'first citizen:\nbefore we proceed any further, hear me speak.\n\nall:\nspeak, speak.\n\nfirst citizen:\nyou'

In [ ]:
'''
The data is not clean. It contains occurances of titles and subtitles which might interfere with the model's ability to learn the laguage.

The next few cells clean the data
'''
prev = -1 #index of last group of '\n'
prev_word_idx = 1 #index of the last item that was not '\n'
prev_n = -1
continuous= 0 #counting the consecutive '\n'
list_idx_to_remove = []
for i in range(2, len(text)):
  if text[i]=='\n':
    continuous+= 1
  else:
    prev_word_idx = i
    continuous = 0
  if continuous>1:
    if (prev> -1) and (i - prev)==5:
      if len(text[i-3])<40 and text[i-3]!='\n':
        list_idx_to_remove.append(i-3)
        #remove next sentence if only the first is removed
        if len(text[i-2])<40 and text[i-2]!='\n':
          list_idx_to_remove.append(i-2)
    if(prev>-1) and (i-prev)==4:
      if len(text[i-2])<40 and text[i-2]!='\n':
        list_idx_to_remove.append(i-2)
    if continuous>2:
      list_idx_to_remove.append(prev_word_idx)
    prev = i-continuous + 1

print(len(list_idx_to_remove), list_idx_to_remove[:5])

list_idx_to_remove = list(set(list_idx_to_remove))
list_idx_to_remove.sort()
print(len(list_idx_to_remove))
for idx_to_remove in list_idx_to_remove[11:13]:
  print(text[idx_to_remove -3:idx_to_remove+3])
  print(text[idx_to_remove])

cleaned_text = []
continuous = 0 #the number of consecutive '\n'

for i in range(len(text)):
  line = text[i]
  if line=='\n':
    continuous +=1
  else:
    continuous = 0

  if i in list_idx_to_remove:
    continue

  if continuous>3:
    continue
  cleaned_text.append(line)

print(len(cleaned_text), len(text))

cleaned_text = "".join(cleaned_text)

text = cleaned_text.lower()

text[:200]

2 [442990, 919583]
2
1115392 1115394


'first citizen:\nbefore we proceed any further, hear me speak.\n\nall:\nspeak, speak.\n\nfirst citizen:\nyou are all resolved rather to die than to famish?\n\nall:\nresolved. resolved.\n\nfirst citizen:\nfirst, you'

# Understanding Recurrent Neural Networks (RNNs) and LSTMs

## Recurrent Neural Networks (RNNs)

Recurrent Neural Networks (RNNs) are a type of neural network architecture designed for sequence data. Unlike traditional feedforward neural networks, RNNs have connections that loop back within the network, allowing information to persist.

![RNN Architecture](https://drive.google.com/uc?export=view&id=1Cr7Od8Tzm7FVDo5QG5wHn-iFzsANpAfx)

### How RNNs Work

1. **Sequence Data**: RNNs are ideal for sequence data like time series, speech, text, etc.
2. **Hidden State**: The hidden state acts as the network's memory, capturing information from all past time steps.
3. **Shared Parameters**: The same parameters are used for each input, making the network efficient and capable of handling sequences of varying lengths.

---

## Long Short-Term Memory (LSTM) Networks

Long Short-Term Memory (LSTM) units are a special kind of RNN architecture capable of learning long-term dependencies. LSTMs are explicitly designed to avoid long-term dependency issues, making them more effective for sequence modeling tasks.

![LSTM Architecture](https://drive.google.com/uc?export=view&id=1Z0IK859UF8atU1qmQKfoBIeOq6A_V8S8)

### How LSTMs Work

1. **Gates**: LSTMs have a complex cell structure with input, output, and forget gates that control the flow of information.
2. **Cell State**: The cell state acts as a "conveyor belt" that carries relevant information across time steps, mitigating vanishing gradient problems.
3. **Long-Term Dependencies**: LSTMs are capable of learning long-term dependencies thanks to their gating mechanisms.

---

## Understanding Gates in LSTM Units

LSTMs have three main types of gates:

1. **Input Gate**: Determines what information from the current input will be stored in the cell state.
    \[
    i_t = \sigma(W_{ii} x_t + b_{ii} + W_{hi} h_{t-1} + b_{hi})
    \]
   
2. **Forget Gate**: Decides what information from the cell state should be thrown away or kept.
    \[
    f_t = \sigma(W_{if} x_t + b_{if} + W_{hf} h_{t-1} + b_{hf})
    \]

3. **Output Gate**: Determines what information from the cell state is sent as output.
    \[
    o_t = \sigma(W_{io} x_t + b_{io} + W_{ho} h_{t-1} + b_{ho})
    \]

### How Gates Work

- **Input Gate**: Takes the current input \( x_t \) and the previous hidden state \( h_{t-1} \), and decides which values will be updated in the cell state.
  
- **Forget Gate**: Takes the current input \( x_t \) and the previous hidden state \( h_{t-1} \), and decides which values in the cell state should be discarded.

- **Output Gate**: Takes the current input \( x_t \) and the modified cell state, and decides what should be the output \( h_t \).

The gates use the sigmoid activation function \( \sigma \) to squash values between 0 and 1, helping the LSTM unit to learn which information is important and which can be forgotten.


In [ ]:
from torch.utils.data import DataLoader, Dataset, random_split
from torch.autograd import Variable

In [ ]:
from torch.utils.data import Dataset

class ShakespeareDataset(Dataset):
    def __init__(self, text, sequence_length, chars, char_to_index, index_to_char):
        self.text = text
        self.sequence_length = sequence_length
        self.chars = chars
        self.char_to_index = char_to_index
        self.index_to_char =index_to_char
        self.text_indices = [self.char_to_index[char] for char in text]

    def __len__(self):
        return len(self.text) - self.sequence_length - 1

    def __getitem__(self, index):
        sequence = self.text_indices[index:index+self.sequence_length]
        target = self.text_indices[index+self.sequence_length]
        return torch.tensor(sequence), torch.tensor(target)


In [ ]:
import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import DataLoader, TensorDataset
# Hyperparameters
sequence_length = 300
BATCH_SIZE = 128
hidden_size = 256
num_layers = 2
learning_rate = 0.0001
num_epochs = 3

text = text[:300000]

chars = sorted(list(set(text)))
char_to_index = {char: index for index, char in enumerate(chars)}
index_to_char = {index: char for index, char in enumerate(chars)}

shakespeare_dataset = ShakespeareDataset(text, sequence_length=sequence_length, chars=chars, char_to_index=char_to_index, index_to_char=index_to_char)

train_size = int(0.8 * len(shakespeare_dataset))
val_size = len(shakespeare_dataset) - train_size
train_dataset, val_dataset = torch.utils.data.random_split(shakespeare_dataset, [train_size, val_size])

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, drop_last=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, drop_last=True)


In [ ]:
# Define the model
class CharRNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size, dropout):
        super(CharRNN, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, dropout=dropout)
        self.fc = nn.Linear(hidden_size, output_size)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, h0):
        x, hidden = self.lstm(x, h0)
        # take only the last output
        x = self.dropout(x)
        x = x[:, -1, :]
        x = x.contiguous().view(-1, hidden_size)
        #print(x.shape)
        # produce output
        out = self.fc(x)
        return out, hidden

    def init_hidden(self, batch_size):
        weight = next(self.parameters()).data
        hidden = (weight.new(self.num_layers, batch_size, self.hidden_size).zero_(),
                  weight.new(self.num_layers, batch_size, self.hidden_size).zero_())
        return hidden

In [ ]:
# Initialize the model
model = CharRNN(1, hidden_size, num_layers, len(chars), 0.2)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [ ]:
model.cuda()

CharRNN(
  (lstm): LSTM(1, 256, num_layers=2, batch_first=True, dropout=0.2)
  (fc): Linear(in_features=256, out_features=37, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [ ]:
# Training loop
best_loss = 1e6
for epoch in range(num_epochs):
    model.train()
    h = model.init_hidden(BATCH_SIZE)
    for batch_idx, (X_batch, y_batch) in enumerate(train_loader):
        X_batch = X_batch.to(torch.int64)
        y_batch = y_batch.to(torch.int64)

        #X_batch_onehot = torch.nn.functional.one_hot(X_batch, num_classes=len(chars)).float()
        X_batch = X_batch.unsqueeze(2).float()
        h = tuple([each.data.cuda() for each in h])
        X_batch = X_batch.cuda()
        try:
            outputs, h = model(X_batch, h)
        except Exception as e:
            print(X_batch.shape, h[0].shape, h[1].shape, e)
            raise(e)
        #y_batch = torch.nn.functional.one_hot(y_batch, num_classes=len(chars)).float()
        #print(y_batch.size(), outputs.size())
        y_batch = y_batch.cuda()
        loss = criterion(outputs, y_batch.long())

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch_idx % 100 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Batch [{batch_idx+1}/{len(train_loader)}], Loss: {loss.item():.4f}')

    model.eval()
    val_loss = 0
    with torch.no_grad():
        h = model.init_hidden(BATCH_SIZE)
        for X_batch, y_batch in val_loader:
            X_batch = X_batch.to(torch.int64)
            y_batch = y_batch.to(torch.int64)

            X_batch = X_batch.unsqueeze(2).float()
            X_batch = X_batch.cuda()
            h = tuple([each.data.cuda() for each in h])
            #y_batch = torch.nn.functional.one_hot(y_batch, num_classes=len(chars)).float()
            y_batch = y_batch.cuda()
            outputs, h = model(X_batch, h)
            loss = criterion(outputs, y_batch.long())
            val_loss += loss.item()
    print(f"Epoch {epoch+1}/{num_epochs}, Val Loss: {val_loss/len(val_loader)}")
    if val_loss < best_loss:
        torch.save(model.state_dict(), 'model.pth')
        print('saving...')
        best_loss = val_loss
print("Training complete.")

Epoch [1/3], Batch [1/1873], Loss: 3.6273
Epoch [1/3], Batch [101/1873], Loss: 3.0985
Epoch [1/3], Batch [201/1873], Loss: 2.9323
Epoch [1/3], Batch [301/1873], Loss: 3.0144
Epoch [1/3], Batch [401/1873], Loss: 3.0144
Epoch [1/3], Batch [501/1873], Loss: 2.7701
Epoch [1/3], Batch [601/1873], Loss: 2.8728
Epoch [1/3], Batch [701/1873], Loss: 2.9577
Epoch [1/3], Batch [801/1873], Loss: 2.9850
Epoch [1/3], Batch [901/1873], Loss: 2.7157
Epoch [1/3], Batch [1001/1873], Loss: 2.9154
Epoch [1/3], Batch [1101/1873], Loss: 2.8940
Epoch [1/3], Batch [1201/1873], Loss: 2.7707
Epoch [1/3], Batch [1301/1873], Loss: 2.8575
Epoch [1/3], Batch [1401/1873], Loss: 2.8706
Epoch [1/3], Batch [1501/1873], Loss: 2.8446
Epoch [1/3], Batch [1601/1873], Loss: 2.7499
Epoch [1/3], Batch [1701/1873], Loss: 2.7365
Epoch [1/3], Batch [1801/1873], Loss: 2.8724
Epoch 1/3, Val Loss: 2.733549403838622
saving...
Epoch [2/3], Batch [1/1873], Loss: 2.7530
Epoch [2/3], Batch [101/1873], Loss: 2.5567
Epoch [2/3], Batch [20

In [ ]:
import random

def generate_text(model, initial_sequence, sequence_length, generate_length=100):
    # Initialize hidden state
    h0 = model.init_hidden(1)  # Batch size is 1 for inference
    initial_sequence = initial_sequence.lower()
    # Prepare initial sequence tensor
    text_indices = [char_to_index[char] for char in initial_sequence]
    initial_sequence = torch.tensor(text_indices)
    #initial_sequence = initial_sequence.unsqueeze(0)
    # Initialize generated text with the initial sequence
    generated_text = initial_sequence.unsqueeze(0)[0].tolist()

    with torch.no_grad():
        for i in range(generate_length):
            # Forward pass
            initial = initial_sequence.unsqueeze(0).unsqueeze(2).float()
            #initial_sequence_onehot = torch.nn.functional.one_hot(initial, num_classes=len(chars)).float().cuda()
            h0 = tuple([each.data.cuda() for each in h0])
            #print(initial_sequence_onehot.shape)
            initial = initial.cuda()
            output, h0 = model(initial, h0)

            # Get the predicted character index
            #print(output.shape)
            output = output[-1, :]
            #print(output.shape, output)
            predicted = torch.topk(output, 3).indices
            predicted = predicted.cpu().detach()
            idx = random.randint(0, 2)
            predicted = predicted[idx]
            #print(predicted, predicted.item())
            # Add the predicted character to the generated text
            generated_text.append(predicted.item())
            #print(predicted.unsqueeze(0).shape)
            # Update the initial sequence to include the predicted character
            initial_sequence = torch.cat((initial_sequence[1:], predicted.unsqueeze(0)), dim=0)
            #print(initial_sequence.shape)

    # Convert the generated text from indices to characters
    generated_text = [shakespeare_dataset.index_to_char[index] for index in generated_text]

    return ''.join(generated_text)

# Load the trained model (replace 'model.pth' with your model's filename)
model_path = 'model.pth'
model = CharRNN(1, hidden_size, num_layers, len(chars), 0.2)
model.load_state_dict(torch.load(model_path))
model.eval()
model.cuda()

# Provide an initial sequence to start generating text
initial_sequence = """f, that's off;\ni would you rather had been silent. please you\nto hear cominius speak?\n\nbrutus:\nmost willingly;\nbut yet my caution was more pertinent\nthan the rebuke you give it.\n\nmenenius:\nhe loves your people\nbut tie him not to be their bedfellow.\nworthy cominius, speak.\nnay, keep your place.\n\nfirs """

# Generate text
generated_text = generate_text(model, initial_sequence, sequence_length, generate_length=100)
print("Generated Text:")
print(generated_text)

Generated Text:
f, that's off;
i would you rather had been silent. please you
to hear cominius speak?

brutus:
most willingly;
but yet my caution was more pertinent
than the rebuke you give it.

menenius:
he loves your people
but tie him not to be their bedfellow.
worthy cominius, speak.
nay, keep your place.

firs cndiierssser:::-tee,
wo three,
tour soerers,dn ioreress a wioe tiree the mo hoe aar aaneeeess,
a mav
